# Generated by Django 4.1.1 on 2022-10-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.foodname')),
            ],
            options={
                'verbose_name': 'Food_id',
                'verbose_name_plural': 'Food_ids',
            },
        ),
    ]
