# Generated by Django 4.1.1 on 2022-10-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_foodmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodMaster',
        ),
    ]
